export EC2_HOME=/opt/ec2-api-tools
export JAVA_HOME=/Library/Java/Home
export EC2_PRIVATE_KEY=$HOME/.amazon/pk-LGHQQAYUDJF2B667OVPBZHYT26WXTEZW.pem
export EC2_CERT=$HOME/.amazon/cert-LGHQQAYUDJF2B667OVPBZHYT26WXTEZW.pem
